/**
 * Guards the curated sidebar against orphaned pages. Most sidebar groups in astro.config.mjs are
 * `autogenerate`d, but **Guides is a hand-maintained list** (grouped by intent; the pages' frontmatter
 * `order` is deliberately ignored). So a new guide file builds a reachable page yet silently never appears
 * in navigation unless its slug is also added to the sidebar — a drift this check exists to prevent.
 *
 * It fails when a content page is neither in an autogenerated directory nor explicitly listed (an ORPHAN),
 * or when a listed slug has no corresponding file (a DANGLING entry — a typo or a deleted page).
 *
 * Run (no build needed — reads source + config):  bun run apps/docs/scripts/check-orphan-pages.ts
 * Exits non-zero on any failure so it can gate CI.
 */
import { readdirSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const docsDir = `${root}src/content/docs`;
const config = readFileSync(`${root}astro.config.mjs`, "utf8");

// Reserved standalone pages that are intentionally not in the sidebar (Starlight's not-found page).
const IGNORE = new Set(["404"]);
// The real top-level content directories, so a quoted "dir/name" is only treated as a page slug when `dir`
// is one of them — keeps import specifiers ("astro/config") and Vite aliases ("mithril/openai") from
// looking like sidebar slugs.
const contentDirs = new Set(readdirSync(docsDir, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name));
// Directories Starlight fills automatically — any new file under them is safe.
const autoDirs = new Set([...config.matchAll(/autogenerate:\s*\{\s*directory:\s*["']([^"']+)["']/g)].map((m) => m[1]));
// Content slugs listed explicitly in a curated group, e.g. "guides/self-correction".
const explicitSlugs = new Set(
  [...config.matchAll(/["']([a-z0-9-]+(?:\/[a-z0-9-]+)+)["']/g)].map((m) => m[1]).filter((s) => contentDirs.has(s.slice(0, s.indexOf("/")))),
);
// Standalone pages reached by a direct `link:` (the reference landing, roadmap, …).
const linkSlugs = new Set([...config.matchAll(/link:\s*["']\/([^"']*)["']/g)].map((m) => m[1].replace(/\/$/, "")));

const seen = new Set<string>();
const orphans: string[] = [];
for (const entry of readdirSync(docsDir, { recursive: true })) {
  const rel = String(entry).replaceAll("\\", "/");
  if (!/\.mdx?$/.test(rel)) continue;
  if (rel.startsWith("reference/")) continue; // TypeDoc output — covered by check-symbol-links
  const slug = rel.replace(/\.mdx?$/, "").replace(/\/index$/, "").replace(/^index$/, "");
  seen.add(slug);
  const topDir = slug.includes("/") ? slug.slice(0, slug.indexOf("/")) : "";
  const covered = slug === "" || IGNORE.has(slug) || autoDirs.has(topDir) || explicitSlugs.has(slug) || linkSlugs.has(slug);
  if (!covered) orphans.push(slug);
}

const dangling = [...explicitSlugs].filter((s) => !seen.has(s));

const problems = [
  ...orphans.map((s) => `orphan page (exists but not in the sidebar): ${s} — add its slug to the sidebar in astro.config.mjs`),
  ...dangling.map((s) => `dangling sidebar entry (listed but no file): ${s}`),
];

if (problems.length === 0) {
  console.log(`✓ every docs page is reachable from the sidebar (${seen.size} pages checked)`);
} else {
  console.error(`✗ ${problems.length} sidebar/page mismatch(es):`);
  for (const p of problems) console.error("  - " + p);
  process.exit(1);
}
